### ISSUE TITLE
Snapshots from Test Suite

### ISSUE THREAD

**Issue by teddyrendahl** [pcdshub/typhos#127]
The `show_widget` wrapper in the test suite will show each widget if the `--show-ui` command line option is set. This is nice to visually that the UI is reasonable beyond what could be expected from the test suite. A cool idea from @klauer would be to also stash screenshots of these created widgets and store them somewhere. These could help us pinpoint any regression as well as feed our documentation e.t.c

**Comment by klauer** [comment]
Good idea, @klauer! You should do this.
