### ISSUE TITLE
Typhon Template Paths

### ISSUE THREAD

**Issue by teddyrendahl** [pcdshub/typhos#151]
There should be a list of directories or at least a specified relative path that Typhon looks for templates. This should be specified via environment variable. Not quite sure on actual implementation yet but something like:

`TYPHON_TEMPLATE_PATH=main/path/to/templates;other/extra/templates;`

@klauer has suggested this a couple times, just realizing now how necessary this will be

**Comment by klauer** [comment]
Also a recent discussion topic, @hhslepicka

**Comment by klauer** [comment]
This was solved recently and sped up via display path caching. We use the same paths that PyDM would.
