### ISSUE TITLE
Drag and Drop between ParameterTree

### ISSUE THREAD

**Issue by teddyrendahl** [pcdshub/typhos#179]
Allow devices to be dragged and dropped between parameter trees.

**Comment by klauer** [comment]
As we are using a new docking system for LUCID, rearranging via our own routines is no longer necessary. We could not really compare with https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System even if we tried.

**Comment by hhslepicka** [comment]
I think the new action item would be to transition the panels to be dockable with the new docking system... I will create a new issue for that.
