### ISSUE TITLE
SignalRow

### ISSUE THREAD

**Issue by teddyrendahl** [pcdshub/typhos#181]
Instead of having the smallest unit available in `Typhon` be the `TyphonSignalPanel` you should be able to drag in a single row of the grid. You can choose to align it vertically or horizontally. `TyphonSignalPanel` will need to know how to break up these rows and assemble them into a `QGridLayout`

**Comment by klauer** [comment]
This may still happen in the future, but it's not on our roadmap. Closing for now.
