### ISSUE TITLE
Recognize Disconnections Faster when adding Device

### ISSUE THREAD

**Issue by teddyrendahl** [pcdshub/typhos#189]
# Problem
Currently if you add a disconnected `ophyd.Device` to `TyphonSuite`, a display will be created but error messages are barfed out. All calls to the underlying controls system have `try/except` blocks but they don't communicate well. Therefore, we get an error message for every signal that is introspected and every tool we try add a device to.

# Possible Solution
Do we just want to call `wait_for_connection` at the start of the routine and if not just make a "class" based screen for these devices (i.e no information gained via describe?)

**Comment by hhslepicka** [comment]
Can't you use the `connected` signal to notify the widget and not even try to communicate unless it is connected?

**Comment by teddyrendahl** [comment]
@hhslepicka That is the best idea

**Comment by teddyrendahl** [comment]
Worried this will cause a lot of flashing / resizing. Also probably only want it on first connection? Don't want to connect, then disconnect and redraw for both steps.

**Comment by hhslepicka** [comment]
Why do you say `both steps`?

**Comment by teddyrendahl** [comment]
As in we don't want to:
1. Widget is created we draw a dummy widget because we are disconnected
2. Channel connects and we draw the correct widget based on type
3. Channel disconnect and we go back to dummy mode

**Comment by klauer** [comment]
Bumping this issue, as we really need to take care of it somehow.
