### ISSUE TITLE
Handling of Child Devices

### ISSUE THREAD

**Issue by teddyrendahl** [pcdshub/typhos#192]
Not all sub-devices need to be added to the `ParameterTree`. Some of the should **only** be embeddable (as in they are so simple they do not need the detailed screen)

**Comment by teddyrendahl** [comment]
I want to add that I think these should be included in the engineering screen template. This can be a Python file now which makes it much easier!

**Comment by klauer** [comment]
This is the deep Device tree issue we were discussing @hhslepicka, where things like AreaDetector sub-device `Size` (two components SizeX/SizeY) became a prominent tree member

**Comment by klauer** [comment]
I think this is largely outdated due to the new detailed tree we support. Closing for now.
