### ISSUE TITLE
Resizing in TyphonSuite

### ISSUE THREAD

**Issue by teddyrendahl** [pcdshub/typhos#193]
The `TyphonSuite` should be resizable. Contained widgets should expand to their correct size and not be contracted past the point where they begin having overlap/display issues.

**Comment by teddyrendahl** [comment]
A simple deletion of the line: 
https://github.com/pcdshub/typhon/blob/bdf7db8b587a7ca84a56b3eed54b8fd647ae94a3/typhon/suite.py#L99

Let's the `TyphonSuite` resize but strange things happen when you close / add widgets.
![resizing](https://user-images.githubusercontent.com/25753048/54721786-29924800-4b20-11e9-83dd-909b82a6ce52.gif)

**Comment by klauer** [comment]
This is largely fixed now, with size hints and size policies tweaked as part of the detailed tree.
