### ISSUE TITLE
Rename package to `typhos`

### ISSUE THREAD

**Issue by klauer** [pcdshub/typhos#223]
It's been decided that the best way around the PyPI package naming conflict is a rename of typhon to a synonym "typhos" which is not currently on PyPI.

TODO:
- [x] Rename package
- [x] Keep `typhon` import working, alias + deprecate old names
- [x] Upload to PyPI as soon as possible (lest we go through this again)
- [x] Update conda channels (pcdsenvs, conda-forge?)
- [x] Review class renames
- [x] Double-check documentation
- [x] Update doctr key
- [ ] Others?

P.S. Sorry, @teddyrendahl...

**Comment by teddyrendahl** [comment]
I expected a few to defame my legacy, but not like this...

In all serious-ness, I'm sorry for following the Qt naming convention and pre-pending every class with the package name. Probably an unnecessary decision. I think this will also break any older saved `.ui` files.

**Comment by hhslepicka** [comment]
As long as we keep the `Plugins` they will survive! 
The idea is to maintain the name for Designer Plugins to avoid crashes and in the future to find a way to replace them maybe with an utility tool at ~~Typhon~~Typhos to fix UI files with changes that came along the way.

**Comment by ZLLentz** [comment]
Some runner-up names:
`typhoon`
`typhone`
`typhn`
`pydm-ophyd-auto-ui`

**Comment by hhslepicka** [comment]
Closed via #224 and #225
