### ISSUE TITLE
Typhos fails to install via PyPI

### ISSUE THREAD

**Issue by hhslepicka** [pcdshub/typhos#231]
## Expected Behavior

`pip install typhos` should work properly.

## Current Behavior

As reported by Dylan (ALS) it is currently not working.

**Comment by dylanmcreynolds** [comment]
The error I see is:

Found existing installation: typhos 0.6.0+11.gdb212b9
Uninstalling typhos-0.6.0+11.gdb212b9:
  Would remove:
    /home/dylan/work/xicam/env/bin/typhon
    /home/dylan/work/xicam/env/bin/typhos
    /home/dylan/work/xicam/env/lib/python3.7/site-packages/typhos.egg-link
Proceed (y/n)? y
  Successfully uninstalled typhos-0.6.0+11.gdb212b9
(env) dylan@stelvio:~/work/xicam$ pip install typhos
Collecting typhos
  Using cached typhos-0.6.0.tar.gz (69 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/dylan/work/xicam/env/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-me2lrluo/typhos/setup.py'"'"'; __file__='"'"'/tmp/pip-install-me2lrluo/typhos/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-me2lrluo/typhos/pip-egg-info
         cwd: /tmp/pip-install-me2lrluo/typhos/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-me2lrluo/typhos/setup.py", line 5, in <module>
        with open('requirements.txt') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
