### ISSUE TITLE
Add "typhos related display button"

### ISSUE THREAD

**Issue by klauer** [pcdshub/typhos#238]
* Requires either ophyd class, ophyd class name + prefix
* Or happi entry name

**Comment by klauer** [comment]
I don't recall what this means. If @hhslepicka doesn't, we should close this.

**Comment by hhslepicka** [comment]
I know what this is...
This is to create a new Widget that is Typhos-aware in which you can open a new typhos screen related to an ophyd class or happi entry name.

Basically the PyDMRelatedDisplayButton but replacing the filename with a Typhos equivalent.
