### ISSUE TITLE
Typhos Template Discussion/Implementation

### ISSUE THREAD

**Issue by ZLLentz** [pcdshub/typhos#248]
See https://github.com/pcdshub/pcdsdevices/pull/382

**Comment by klauer** [comment]
Copying my comment here for further discussion - please copy in a summary of your thoughts as well.

Order of template determination
-------------
1. User/developer -level override somehow?
2. `happi` entry template field
3. Class/instance-specified templates
   a. Fully qualified class path, e.g., `{pcdsdevices.whatever.ClassName}.{detailed}.ui`
   b. Bare class path, e.g., `{ClassName}.{detailed}.ui`
   c. Repeat the above for `cls.mro()[1:]`

Other
-------------
~* Template file searching should likely be cached~
* I also wonder if we could have any of the above alternate templates for screens swapped dynamically with, say, a context menu option. This could allow for the operator to fall back to a screen easily if we incorrectly specify it somehow.

**Comment by ZLLentz** [comment]
Adding:

- Use class `mro` to pick a fallback screen, e.g. positioner subclasses can default to the `ophyd.positioner.PositionerBase.ui` file
- Provide option in `TyphosSignalPanel` to omit signals that are specified elsewhere in the template

**Comment by hhslepicka** [comment]
The context menu option is a great idea. I will try to take a look at it.

**Comment by klauer** [comment]
I like the idea of:
>Provide option in TyphosSignalPanel to omit signals that are specified elsewhere in the template, e.g. no reason to show the motor's readback in the middle of the big sub-tab if we have it front and center above

I think it's much more complicated than I had first imagined. I'd like to move it to a separate issue and consider this one closed once #257 is in.

**Comment by ZLLentz** [comment]
I imagine it would require a bit of a refactor to accomplish that item... I think it's a good thing to work towards but maybe not the highest priority

**Comment by klauer** [comment]
Thanks for the input, @ZLLentz. Closing.
