### ISSUE TITLE
Enhance Disconnected Signal Representation

### ISSUE THREAD

**Issue by hhslepicka** [pcdshub/typhos#258]
## Expected Behavior
From Tim Maxwell:

> My mistake re: purple of course. Feedback is simply something that doesn't get false hope. Instant visual feedback without mouse over I'd think is preferred. Maybe a broken icon/disconnect of some kind :broken_heart:.

From William Schlotter:
> This animation seems to make me feel that I'm going to see a PV soon.   I'm always disappointed...could it be a red X?

## Current Behavior

Currently the system shows an animation while the signal does not receive the connection callback.

## Possible Solution
As pointed above, one possible solution is to replace the animation with a broken link static representation along with a tooltip to clarify.

## Steps to Reproduce (for bugs)

1. Open a Typhos screen for a disconnected device

## Context

This issue affects users as it gives the hope that the signal will be connected soon and not always that is true.

## Your Environment

Development Environmnet.

**Comment by ZLLentz** [comment]
Perhaps we start with the existing GIF, as there may be cases where we have delayed setup, but then switch to the broken icon after a short timeout?
