### ISSUE TITLE
Switch from Point sized to Pixel sized for Fonts

### ISSUE THREAD

**Issue by hhslepicka** [pcdshub/typhos#260]

**Comment by klauer** [comment]
https://doc.qt.io/qt-5/highdpi.html

**Comment by klauer** [comment]
Current master:

Windows
![image](https://user-images.githubusercontent.com/5139267/81754174-5616cb00-946a-11ea-857f-0a123b440cc1.png)

OSX
<img width="730" alt="image" src="https://user-images.githubusercontent.com/5139267/81754204-6b8bf500-946a-11ea-94db-d28554ddcf92.png">

Note the difference in title font vs row label font with a high-dpi display on the two platforms.

This appears to be the case with or without `﻿QT_ENABLE_HIGH_DPI_SCALING` set. Also, `QT_SCALE_FACTOR` is fun to play with.

**Comment by klauer** [comment]
Changing the title stylesheet to `font: 20px bold serif`:
![image](https://user-images.githubusercontent.com/5139267/81839560-8eff8000-94fc-11ea-9fcc-a585005205c8.png)

Changing the title stylesheet to `font: 20pt bold serif`:
![image](https://user-images.githubusercontent.com/5139267/81839711-c2daa580-94fc-11ea-8492-7745b83060b4.png)

Clearly the pixel-based values are more consistent.
