### ISSUE TITLE
CLI Full Class Edge Case

### ISSUE THREAD

**Issue by ZLLentz** [pcdshub/typhos#271]
## Expected Behavior

Should be able to load devices like `typhos "pcdsdevices.device_types.PPM[{'prefix':'IM3L0:PPM', 'name':'im3l0'}]"` without a `happi` configuration

## Current Behavior

If `happi` is installed and no `happi` config is found, there will be an error raised regardless of whether I asked for a `happi` name or a class designation as above

## Possible Solution

Locally I removed this line to help test the current PR: https://github.com/pcdshub/typhos/blob/1e4bb1bcd6c7b0165e3cedda47d9c4e42c900b9e/typhos/cli.py#L92
This isn't a solution but it shows where the exception is raised, you can see we enter this block after verifying a `happi` import but without checking if there is a config.

Solving this looks like a pretty annoying refactor.

## Steps to Reproduce (for bugs)

1. Unset any `happi` config environment variables
2. Make sure `happi` is still installed
3. Invoke `typhos` with an explicit class and args

## Context

I was just trying to help review the sick composite signal panel PR

## Your Environment

Current master typhos in development mode

**Comment by ZLLentz** [comment]
I was going to hash out a fix for this today but I got side-tracked

**Comment by klauer** [comment]
Closed by #281. If I missed something, please reopen this.
