### ISSUE TITLE
Revisit original SignalPanel destroy-and-recreate functionality

### ISSUE THREAD

**Issue by klauer** [pcdshub/typhos#273]
The SignalPanel creates only signals requested by the user.

If the user-requested signal kinds are changed, the widgets are destroyed and new ones are re-created.

The new CompositeSignalPanel selects _everything_ and then shows/hides based on user filters.

(Path forward not clear just yet - this is more of a reminder than anything)

**Comment by klauer** [comment]
OK, I think what we should do is the following:

* Signal panels always create rows for all signals
* Signals which would be shown based on the filters will have regular Typhos/PyDM widgets that try to connect
* Signals which would not be shown based on the filters will have a stub widget akin to TyphosLoading
* If updates to the filters makes new signals shown, visibility will be changed for those already created, and new widgets will be created for those not previously shown

Additionally,
* By default, the tree should have omitted signals as hidden

**Comment by hhslepicka** [comment]
I like this idea but may I suggest instead of switching the widget back and forth that we implement a `disconnectWhenNotVisible` property for Typhos widgets and leverage that with the existing logic of making them invisible when filtered? That would avoid the need to keep recreating widgets.

**Comment by klauer** [comment]
I'm not sure I follow @hhslepicka. Let me show an example of what I'm thinking:

Let's say we have an omitted signal "test".
1. Omitted signals are not shown by default.
2. A row "test" gets created with a stand-in widget (with no channel, no connection, nothing special about it)
3. The user selects "show omitted signals"
    a. The filter method gets called
    b. Other widgets that are already created and with a channel that match the filter are set to be visible
    c. Once it reaches the row "test", it sees that no widget has been created. It creates the TyphosLoading widget while waiting for its connection callback
    d. Connection callback happens, widget type is determined, widget is updated
4. If the user now selects "hide omitted signals"; all previously created widgets will be hidden (not destroyed)

**Comment by hhslepicka** [comment]
@klauer I like the idea... what I was suggesting was to add an option to disconnect the channel associated with a given widget when it is hidden... that will easy up on the CPU and network depending on what it is attached to. Maybe it is not much of a good idea?

**Comment by klauer** [comment]
Got it. It seemed like you were suggesting widgets were still getting destroyed when filtered.

That seems a good idea - when the PR comes around would you mind helping with that part?

**Comment by hhslepicka** [comment]
Oh, no no on the destroy... sorry about that...
I can for sure help with that when the PR is up.
