### ISSUE TITLE
Initial TyphosSuite size is too small

### ISSUE THREAD

**Issue by klauer** [pcdshub/typhos#304]
See:

![image](https://user-images.githubusercontent.com/5139267/81872433-92abfa80-952e-11ea-8f4b-6e18c4736275.png)

This should be resized to fit the display.

**Comment by hhslepicka** [comment]
this issue was introduced by this change:
https://github.com/pcdshub/typhos/pull/292/files#diff-aec38c255920d58844fabceb2eba0967R770-R777

Maybe we can call a `.adjustSize` after setting it all up (https://doc.qt.io/qt-5/qwidget.html#adjustSize)

**Comment by klauer** [comment]
I've tried that and had no luck - it has no real effect. Any other ideas?

**Comment by hhslepicka** [comment]
I will take a stab at it later today.
