### ISSUE TITLE
Clean default templates, adding a 'read' (or normal) panel

### ISSUE THREAD

**Issue by klauer** [pcdshub/typhos#320]
Available kinds:
* Hinted (= hinted | normal)
* Normal
* Config
* Omitted

Desired layout: 

```
Title     [Switcher] [Config]
-----
[Hinted signal panel]

[ (X) Normal panel tab ] [ Configuration panel tab ]
|---------------------------------------------------|
|  Normal panel: Normal but not hinted signals      |
|  Configuration panel: config kind only            |
|---------------------------------------------------|
```

Thoughts relevant to this suggested change:

_Originally posted by @ZLLentz in https://github.com/pcdshub/typhos/issues/250#issuecomment-629479660_
> ... I like the read/config as panel tabs, but only because we may be losing the omitted tab and the config tab will be lonely. I don't suppose it would hurt to do some basic heuristics on the number of hinted + reads and create the panel tab for read only if there are a lot of them?

(_Originally posted by @hhslepicka in https://github.com/pcdshub/typhos/issues/250#issuecomment-629495529_):
> - I don't believe we will have many smaller devices based on what I saw at the pcdsdevices and looking at also devices ready to play from Ophyd.
> - Since the ratio of small devices to large ones is pending to large devices I would say it should take precedence on design.
> - Even if it becomes a bit worst for smaller devices, I believe that the trend is for them to get templates, right?

**Comment by klauer** [comment]
Here's what this might look like:

<img width="619" alt="image" src="https://user-images.githubusercontent.com/5139267/82101311-10a00b00-96c1-11ea-8b8d-a817500c8640.png">

Not bad, but the separation of setpoint/readback isn't great. I think this is less a flaw of the redesign as it is of the `Kind` system (or our current component kind specifications.)

**Comment by ZLLentz** [comment]
Stuff like this makes me want to expand the `kind` system or have a richer "metadata" system for things that matter in a control system. `kind` stops right at the line of "these designations are useful to know for running a `bluesky` plan"

**Comment by klauer** [comment]
Agreed, @ZLLentz - that would be _really_ nice. I think that may be outside of the scope of what NSLS-II wants from ophyd, though I can't imagine they would be against it were we to do the work on adding it.

**Comment by hhslepicka** [comment]
Agreed as well. We could brainstorm it next week and propose the idea to the NSLS-II folks. That would allow us to leave kind alone and have a better suited metadata for UI field.

**Comment by ZLLentz** [comment]
If we brainstorm this, we should try to keep it open enough to be useful for applications beyond the current scope of `typhos`, or else we'll just be making the next "kind" and find ourselves making a third way to attach metadata to a signal later.
