### ISSUE TITLE
BUILD_DOCS CI needs fixing

### ISSUE THREAD

**Issue by klauer** [pcdshub/typhos#334]
https://github.com/pcdshub/typhos/blob/master/.travis.yml#L68

Docs aren't building as the secure env var is unavailable until merged to master:
https://travis-ci.org/github/pcdshub/typhos/jobs/689424728

Refactor to build docs regardless of the key if `BUILD_DOCS` is set, but only deploy if the key is available.

**Comment by hhslepicka** [comment]
I am working on a branch to use the new system with shared configs from pcds-ci-helpers. It will probably help with this as it introduces the new job of building the docs as part of tests.
