### ISSUE TITLE
PositionerWidget fails for StatePositioner

### ISSUE THREAD

**Issue by ZLLentz** [pcdshub/typhos#339]
## Expected Behavior

- Unsure, might actually need changes in `pcdsdevices`
- This device will want a combo box (it probably doesn't even want the `PositionerWidget`)
- This device will probably be forced into a `PositionerWidget`, being a subclass of `PositionerBase`

## Current Behavior

![image](https://user-images.githubusercontent.com/10647860/82699851-4776a380-9c22-11ea-9cf7-090e283f775d.png)

**Comment by ZLLentz** [comment]
If there's no obvious way to handle a non-float Positioner, I will slot this into the states refactor in pcdsdevices

**Comment by klauer** [comment]
We could refactor the template to check `setpoint.describe()` and hide/show an alternate frame, maybe?

This could be done much more easily if https://github.com/pcdshub/typhos/issues/312 were in, as we could generically say "show me the readback widget here" and "show me the setpoint widget here".

**Comment by klauer** [comment]
Or, failing the above, just using a separate template entirely for the state positioners, despite the code duplication that would be involved in that.

**Comment by ZLLentz** [comment]
Something to note here is that the `StatePositioner` doesn't actually have most of the signals requested by this widget (it just has a `state` signal that is both the read and the write for the position). So the separate template would have almost no similarities with the original.

I was also considering whether or not these devices really classify as positioners (e.g. should they stop depending on `PositionerBase`?) But after re-reading the code in ophyd I think it is appropriate. 

A related thought is that this widget seems to assume that it will find signals similar in function to `EpicsMotor`. Does this mean that the positioner widget is truly an epics motor widget? I think this is somewhat the case, though a few changed attributes make it work for `PVPositioner` too. I don't think there is any way to get it to work for `PsuedoPositioner`.

A lot of these base class definitions in ophyd are based on the functional API rather than on the composite signal names, making it hard to generalize for subclasses in the screens here.

**Comment by klauer** [comment]
I think you'd expect a setpoint combobox, a readback label, and maybe a stop button? So long as the positioner widget hides the unavailable components, it seems like it'd still be OK. (Ideal - no, but sufficient - probably).

`PseudoPositioner` itself wouldn't work, but the detailed view of `PseudoSingle` and `EpicsMotor` individual components _should_ in theory.

Very true regarding functionality over component names.

We may get to a point where we're inserting "component interface" mixins for typhos to pick the right screen (i.e., an interface class that guarantees the existence of certain component names)

**Comment by ZLLentz** [comment]
I think you're right about what the template should look like. (And in the back of my head I'm sad that I didn't put a stop button on the states interface)
