### ISSUE TITLE
Attempt to use medm -> pydm converter for AreaDetector screens

### ISSUE THREAD

**Issue by klauer** [pcdshub/typhos#340]
https://github.com/BCDA-APS/adl2pydm

attn @prjemian, do you think adl2pydm will work sufficiently for Area Detector-provided screens by chance?

**Comment by prjemian** [comment]
Mostly, yes.  Almost all those screens use simple text labels, entry widgets, push buttons, and a few popup lists.

I believe there is still work to do to get adl2pydm to a 1.0rc1 level.  But the simple AD screens will probably work.

**Comment by klauer** [comment]
That's great to hear - thanks, @prjemian! I'm hopeful we'll have some spare cycles to help contribute and get you closer to that 1.0rc1 level, too, if it works well enough in these beginning stages.

**Comment by klauer** [comment]
This is _very_ promising. Thanks again @prjemian. We'll be able to do something with this:

<img width="1263" alt="image" src="https://user-images.githubusercontent.com/5139267/82961281-b715c700-9f71-11ea-9624-ded2be3ff5bb.png">

Auto-generated screen for:

```python
class MyDetector(ophyd.SimDetector):
    tiff1 = ophyd.Component(ophyd.TIFFPlugin, 'TIFF1:')
    stats1 = ophyd.Component(ophyd.StatsPlugin, 'Stats1:')
    roi1 = ophyd.Component(ophyd.ROIPlugin, 'ROI1:')
```

with _only_ the `TIFFPlugin` converted as a test.

Things to address or at least look into (which occurred to me after the above test):
- [ ] Stylesheet clashes with the typhos-distributed one
- [ ] Post-screen conversion hook for prefix fix-up (`$(P)$(R)` needs to become `$(prefix)`; which `sed` took care of in my example easily enough)
- [ ] Custom file name mapping `NDFileTIFF.ui` -> `TIFFPlugin.detailed.ui`
- [ ] How do we get the display switcher in these screens? This is a fairly integral part of typhos now, which I think people will start expecting.
- [ ] Image button for image plugins?

**Comment by prjemian** [comment]
Nice!

**Comment by klauer** [comment]
With https://github.com/BCDA-APS/adl2pydm/pull/55 we can improve the above easily enough:
<img width="970" alt="image" src="https://user-images.githubusercontent.com/5139267/83057464-c77a8000-a00b-11ea-8d27-1242833500db.png">

**Comment by klauer** [comment]
Follow-up in #345 for the switcher

Repository of converted screens for all non-beta tagged versions of ADCore: https://github.com/pcdshub/typhos-displays

**Comment by klauer** [comment]
Moving issue to pcdshub/typhos-displays.
