### ISSUE TITLE
Create new screens repository (repositories?)

### ISSUE THREAD

**Issue by klauer** [pcdshub/typhos#342]
Option 1

* ophyd built-in devices remain in repo `typhos`
* Repo `pcds-typhos-screens` (pcds-specific screens)

Option 2

* Repo `typhos-screens` (ophyd built-in devices, useful for other facilities)
* Repo `pcds-typhos-screens` (pcds-specific screens)

Option 3
* ?

Somewhat related to https://github.com/pcdshub/typhos/issues/336

**Comment by klauer** [comment]
Also somewhat related - a 'screen' directory entrypoint for pydm (typhos) might be useful to reduce the amount of environment variable directories that have to be set. (Similar to https://github.com/pcdshub/pyqt-designer-plugin-entry-points/ if we ever get it off the ground)

**Comment by klauer** [comment]
Might also consider submodules (as awful as they are) for screen repositories within `typhos`.

`typhos/ui/{submodules}`
Then, we could even further break things up if desirable: `typhos-area-detector-screens`

**Comment by ZLLentz** [comment]
Seems like you went with option 2, but with a rename: repo `typhos-displays` (and later we'll likely add `pcds-typhos-displays`)

I think it is correct to keep them separated like this.

**Comment by klauer** [comment]
No real decision was made - I just needed a place to toss the areadetector screens in case someone wanted to try them.

**Comment by klauer** [comment]
We have since made:

https://github.com/pcdshub/vacuumscreens
and
https://github.com/pcdshub/ecs-pydm-ui
and we have displays inside pcdsdevices:
https://github.com/pcdshub/pcdsdevices/tree/master/pcdsdevices/ui
