### ISSUE TITLE
Error Clear on PositionerWidget

### ISSUE THREAD

**Issue by ZLLentz** [pcdshub/typhos#343]
## Expected Behavior

Define API for error clear signal, have a button appear in the screen to clear the error state. This would simply put to the error clear signal.

## Current Behavior

No such signal API

## Context

Had to switch to the tree template to clear my NC error

**Comment by klauer** [comment]
`Clear error` button could just hide the shown error in all cases, and `set` the associated `clear` signal if it exists, I suppose?

**Comment by ZLLentz** [comment]
Yeah, I think that makes sense. Sorry for not making this more detailed, I wanted to jot it down during the morning checkout session and get back to checking out.

Looking at existing classes, we have two instances of error clearing, but both are done via calling methods (which, in turn, put to signals). In each case this is a method called `clear_error`. I'm not sure that calling methods on the object is desirable here. I'd favor something like a `clear_error_cmd` signal (but less verbose).

**Comment by klauer** [comment]
Method calling definitely comes with its own issues, which `clear_error_cmd.set()` resolves easily. 

How baked in are those methods? Could they become `._clear_error` with `clear_error` becoming a soft signal that calls the former?

**Comment by ZLLentz** [comment]
I am ok with making them soft signals that call a method. I think that is a more correct way to do it in general. In some cases if the method is truly just doing a single put or set then the direct signal should probably be used.

**Comment by klauer** [comment]
`clear_error` as a method returning a status object was the route chosen in https://github.com/pcdshub/typhos/pull/447

I think this is good to close, unless we want to circle back and make a signal API convention as described above. Re-open if you disagree.
