### ISSUE TITLE
Testing IOC

### ISSUE THREAD

**Issue by teddyrendahl** [pcdshub/typhos#41]
## Expected Behavior

We should create a testing IOC. This way we can see what our screens look like with connected widgets. This can either be in `caproto` or `pcaspy`

## Current Behavior

Tests run on disconnected widgets

**Comment by hhslepicka** [comment]
I would say that we can take `caproto` for a spin and in the worst case fall back to either pcaspy or really a `docker` image with epics Simulated IOCs.

**Comment by teddyrendahl** [comment]
Nice! I'm into that. It would be nice if what ever solution we have works on MacOS as well. I have a shell of it:

https://github.com/teddyrendahl/typhon/tree/caproto_suite

**Comment by teddyrendahl** [comment]
This might be entirely unnecessary with new plans to have a fake data plugin in PyDM
