### ISSUE TITLE
pcdsdevices _OptionalEpicsSignal signals time out and fail to generate a widget

### ISSUE THREAD

**Issue by klauer** [pcdshub/typhos#415]
## Current Behavior

`_OptionalEpicsSignal` is a pcdsdevices hack to make an EpicsSignal component optional.

## Expected Behavior
`_OptionalEpicsSignal` should work the same as `EpicsSignal` in the case when the signal is present.

## Possible Solution
This may require fixing in pcdsdevices rather than in typhos. I have not looked into details.

## Steps to Reproduce (for bugs)
1. Add an `_OptionalEpicsSignal` component to a device
2.  Launch a typhos screen and see it fail

## Context
Discovered while developing AT1K4 screens

## Screenshots

<img width="672" alt="image" src="https://user-images.githubusercontent.com/5139267/104515431-ac16b200-55a7-11eb-8023-b4dc298f8483.png">

```
In [1]: at1k4.calculator.blade_03.active
Out[1]: _OptionalEpicsSignal(name='at1k4_calculator_blade_03_active', parent='at1k4_calculator_blade_03', value=1, timestamp=1610567215.343223)
```

**Comment by ZLLentz** [comment]
Oh no

**Comment by klauer** [comment]
I think we're removing `_OptionalEpicsSignal` at some point and should not bother fixing this. 

Closing for now, but if you disagree feel free to re-open.
