### ISSUE TITLE
Test suite gets stuck

### ISSUE THREAD

**Issue by ZLLentz** [pcdshub/typhos#435]
https://travis-ci.com/github/pcdshub/typhos/jobs/495751962#L3247-L3252

I'm not sure what is going on here

**Comment by ZLLentz** [comment]
Locally I see an error dialog that I must dismiss for the test suite to resume, though the test suite also seems to crash
![image](https://user-images.githubusercontent.com/10647860/113444274-6c8e8380-93a8-11eb-9a8f-cb7620b17920.png)

**Comment by ZLLentz** [comment]
From the `Show Details...` button:
```
  File "/cds/home/z/zlentz/github/typhos/typhos/display.py", line 838, in load_best_template
    widget = self._load_template(template)
  File "/cds/home/z/zlentz/github/typhos/typhos/display.py", line 906, in _load_template
    loader = (pydm.display.load_py_file if filename.suffix == '.py'
```

**Comment by klauer** [comment]
Handy exception message! Looks like it's leaking a string path into a method that's expecting a `pathlib.Path`, hmmm

**Comment by ZLLentz** [comment]
Yes, that's also what I thought was happening. We can either find the leak or just `pathlib.Path` the filename here again.

**Comment by ZLLentz** [comment]
Did something structurally change in `pydm`? I'm hitting more issues after resolving that one. I'll just keep documenting them here and trying to fix.

![image](https://user-images.githubusercontent.com/10647860/113445106-0efb3680-93aa-11eb-9d9b-a3fd480b18a3.png)

```
  File "/cds/home/z/zlentz/github/typhos/typhos/display.py", line 838, in load_best_template
    widget = self._load_template(template)
  File "/cds/home/z/zlentz/github/typhos/typhos/display.py", line 911, in _load_template
    return loader(str(filename), macros=self._macros)
  File "/cds/home/z/zlentz/miniconda3/envs/pcds-4.1.0/lib/python3.8/site-packages/pydm/display.py", line 112, in load_ui_file
    f = macro.substitute_in_file(uifile, macros)
  File "/cds/home/z/zlentz/miniconda3/envs/pcds-4.1.0/lib/python3.8/site-packages/pydm/utilities/macro.py", line 28, in substitute_in_file
    template = template_for_file(file_path)
  File "/cds/home/z/zlentz/miniconda3/envs/pcds-4.1.0/lib/python3.8/site-packages/pydm/utilities/macro.py", line 46, in template_for_file
    with open(file_path) as orig_file:
```

**Comment by klauer** [comment]
Hmm, I don't recall seeing anything relevant get merged. This is `v1.10.7` vs `v1.11.0`, right?

**Comment by ZLLentz** [comment]
Yes, I think that's the version change

**Comment by ZLLentz** [comment]
For what it's worth, there isn't a test.ui anywhere in typhos, nor has there ever been

**Comment by klauer** [comment]
Looked through the version diff and I don't see anything really relevant in pydm.

Wonder if this test has just been race-condition laden since the start? Strange we haven't knowingly run into it before/fixed it.

**Comment by ZLLentz** [comment]
The tests do not freeze up when I downgrade my pydm to `v1.10.7`, this is what I'm going to opt to do for today's environment release and leave this as a follow-up for updating pcds-envs's pydm version
