### ISSUE TITLE
Hide options for web docs + jira if not configured with environment variables

### ISSUE THREAD

**Issue by ZLLentz** [pcdshub/typhos#452]
## Expected Behavior

The help menu should not show the jira option if jira is not configured and it should not show the web docs options if the web docs are not configured?

## Current Behavior

All options (jira, web docs, help toggle to web docs) are still there even if they don't do anything

**Comment by klauer** [comment]
The help menu could potentially fall back to just showing docstring information by default - as opposed to being hidden entirely.
