### ISSUE TITLE
Allow use of the sig:// plugin in typhos templates

### ISSUE THREAD

**Issue by ZLLentz** [pcdshub/typhos#454]
## Expected Behavior

We should be able to refer to arbitrary signals in a `typhos` template, for example if my device has a "count" signal, I should be able to include it in designer by setting a PyDM widget's channel to `"sig://{name}_count"`.

## Current Behavior

The `sig://` protocol requires to user the pre-register the signals they want to use with it. This isn't possible by just creating a ui file.

## Possible Solution

When instantiating a typhos template, register the device's signals to the signal plugin.

## Context

Currently creating a tutorial for making templates

## Your Environment

latest pydm/typhos, rhel7 and win10

**Comment by klauer** [comment]
Dotted name access would be nice, too, if possible. Or is two paths like that confusing?

**Comment by ZLLentz** [comment]
I think that's a good idea. It should be possible to include a signal's full dotted path in the registry when we add it.

**Comment by klauer** [comment]
Coming back to making custom PyDM screens, I'm going to bump this as it sure would be nice to have.

**Comment by ZLLentz** [comment]
Let me see how easy/hard this is to do, it bugs me a lot that it isn't possible yet and is a good excuse to slowly chip away at the ui backlog

**Comment by ZLLentz** [comment]
I think this ended up being pretty easy, I'm just looking into if there is a way to make the specification even easier.

Currently, to use this in a template it basically looks like:
- `sig://$(name).user_readback`

I think it's a bit tiresome to macro in the name every time so I'm investigating the potential of:
- `sigattr://user_readback`
- `devattr://y_motor`

Using a channel substitution to `sig://` or `happi://` at runtime as needed.

**Comment by ZLLentz** [comment]
Ok, in the spirit of not letting "perfect" get in the way of "good", I'm going to ignore the diversion and test/polish the expanded sig:// behavior.
