### ISSUE TITLE
Empty space in detailed_tree layout?

### ISSUE THREAD

**Issue by klauer** [pcdshub/typhos#527]
## Expected Behavior
Not excessive blank space between sub-devices

## Current Behavior

Have others seen this?

<img width="915" alt="image" src="https://user-images.githubusercontent.com/5139267/200088017-5cff30a1-9b4b-4e30-bed9-371e8f44be64.png">

## Steps to Reproduce (for bugs)

```
$ typhos at1k4
```

## Context
Improving other aspects of the screen and was surprised by this.

## Your Environment

pcds-5.5.0 on tmo-control

**Comment by ZLLentz** [comment]
oh no that's really obnoxious

**Comment by klauer** [comment]
I think this is largely better now, or at least I haven't seen it in a while. May have been due to the layout refactor.

**Comment by ZLLentz** [comment]
Confirming this is much better now, but the way qt goes it could come back again (with a new issue)
