### ISSUE TITLE
Feedback: Switch default view to 'embedded'

### ISSUE THREAD

**Issue by klauer** [pcdshub/typhos#532]
## Expected Behavior
* Feedback indicates that the default screens show too much information
* Suggestion was that 'embedded' be the default

However, if we work on the existing templates to be more compact or space-efficient may result in a different desired default.

## Current Behavior
Engineering screens are the default

## Related to
#533

**Comment by klauer** [comment]
If they are the primary users of the device, the custom screen can be stored in happi in the current implementation

**Comment by ZLLentz** [comment]
There was a DM request today from Patrick to switch the default to embedded/vertical (so the row widgets display nicely) and/or introduce environment variables to set the defaults
