### ISSUE TITLE
Disable the debug console tool by default

### ISSUE THREAD

**Issue by ZLLentz** [pcdshub/typhos#538]
## Expected Behavior

The debug console tool should be deprecated and removed.

## Current Behavior

The debug console tool causes some problems with the ipython history and in practice has not gotten any usage (to our knowledge).

## Possible Solution

Remove it from the default tools, include it only as a command-line option?

## Context

Came up in discussion today

**Comment by klauer** [comment]
Tools are currently lazily created - that is, until you click on the console it won't be created.

Wouldn't the next step be full removal? Any argument to retain it, considering there is no known usage of it in the wild?

**Comment by nrwslac** [comment]
This is interesting, but, it doesn't seem like a console inside a user facing GUI is super useful unless I am missing the application. Further, why would typhos launch a hutch python session from the CLI? Why not start a hutch python session?

**Comment by ZLLentz** [comment]
The original design goal as I remember it was that it was a way to use device methods as needed, which may not all be exposed in the GUI.
