### ISSUE TITLE
Add smaller positioner widget (row?)

### ISSUE THREAD

**Issue by ZLLentz** [pcdshub/typhos#543]
## Expected Behavior

There should be a re-usable positioner widget variant that is as small as possible- perhaps just a single row- so it can be tiled on a screen.

## Current Behavior

No such variant exists.

## Possible Solution

Create the variant.

## Context

This would be useful for screens that are just an accumulation of many motors.

**Comment by silkenelson** [comment]
Is there a reason not to use the widgets Vincent built? Still too big?

**Comment by ZLLentz** [comment]
There no reason not to re-use and re-package Vincent's ui files as widgets here

**Comment by ZLLentz** [comment]
REF: https://github.com/pcdshub/pydm-ui-lcls1/tree/master/widgets
