### ISSUE TITLE
Class Based Display

### ISSUE THREAD

**Issue by teddyrendahl** [pcdshub/typhos#9]
## Expected Behavior

Often we will want to create a display that can be reused for all devices of the same class. `typhon` should be capable of creating a static `ui` file that can be then reloaded with arbitrary macros identical to the `kwargs` of the original class.

## Current Behavior

Currently only previously instantiated Ophyd objects can be used.

## Possible Solution

Create a screen with a dummy device with macros substituted in for important args and kwargs, then save this as a UI file

**Comment by klauer** [comment]
Classes lack the necessary metadata to generate a useful screen.

We'd need either:
1. A connection to the IOC to get the values to determine the widgets to create
2. Access to the archiver (or some cache of most-recent PV values) + a full PV name

Saving to a .ui is not currently possible, unless we have a custom writer for e.g., suite. 

Making a separate issue for the ui writer as I think it has potential, and closing this one for now.
